# docker-compose.yml
version: "3"
services:
  app:
    build: name-contests/.
    depends_on:
      - postgres
      - mongodb
    ports:
      - "3000:3000"
    environment:
      host: "postgres"
      user: "postgres"
      password: "postgres"
      database: "postgres"
      pg_port: "5432"
      WAIT_HOSTS: postgres:5432, mongodb:27017

  mongodb:
    image: mongo
    ports:
      - "27017"
    volumes:
       - db-data:/data/db

  web:
    build: nginx/.
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"





  postgres:
    image: postgres:9.6.2
    ports:
      - "5432"
    volumes:
       - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
  data_srv:
    image: busybox:latest
    volumes:
       - pg-data:/var/lib/postgresql
       - pgg-data:/var/lib/pgadmin
       - db-data:/data/db
    command: tail -f /dev/null



  db_gui:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
       - pg-data:/var/lib/postgresql
       - pgg-data:/var/lib/pgadmin

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@id3m.net
      - PGADMIN_DEFAULT_PASSWORD=postgres

volumes:
  pg-data:
  db-data:
  pgg-data:
