# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
      - mongodb
    ports:
      - "3000:3000"
    environment:
      host: "postgres"
      user: "postgres"
      password: "postgres"
      database: "postgres"
      pg_port: "5432"
      WAIT_HOSTS: postgres:5432, mongodb:27017

  mongodb:
    image: mongo
    ports:
      - "27017"
    volumes:
       - db-data:/data/db





  postgres:
    image: postgres:9.6.2
    ports:
      - "5432"
    volumes:
       - pg-data:/var/lib/postgresql

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres


  db_gui:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
       - pg-data:/var/lib/postgresql

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@id3m.net
      - PGADMIN_DEFAULT_PASSWORD=postgres

volumes:
  pg-data:
  db-data:
